CONFIG_ZMK_KEYBOARD_NAME="ZMK-TEST"
CONFIG_ZMK_USB=y
CONFIG_ZMK_BLE=n
CONFIG_ZMK_SLEEP=n
CONFIG_ZMK_WPM=n
CONFIG_ZMK_STUDIO=n
CONFIG_ZMK_BATTERY_REPORTING=n
CONFIG_HEAP_MEM_POOL_SIZE=2048
CONFIG_ZMK_KSCAN_DEBOUNCE_PRESS_MS=5
CONFIG_ZMK_KSCAN_DEBOUNCE_RELEASE_MS=5
