name: Build ZMK Firmware

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build ZMK
        uses: zmkfirmware/zmk-build-action@main
        with:
          config: config
